FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 5075

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Services/SeedMicroService/SeedMicroService.csproj", "Services/SeedMicroService/"]
COPY ["Libraries/CommonServices/CommonServices.csproj", "Libraries/CommonServices/"]
RUN dotnet restore "Services/SeedMicroService/SeedMicroService.csproj"
COPY . .
WORKDIR "/src/Services/SeedMicroService"
RUN dotnet build "./SeedMicroService.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./SeedMicroService.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SeedMicroService.dll"]