FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 5104

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Services/CropMicroService/CropMicroService.csproj", "Services/CropMicroService/"]
COPY ["Libraries/CommonServices/CommonServices.csproj", "Libraries/CommonServices/"]
RUN dotnet restore "Services/CropMicroService/CropMicroService.csproj"
COPY . .
WORKDIR "/src/Services/CropMicroService"
RUN dotnet build "./CropMicroService.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./CropMicroService.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CropMicroService.dll"]