FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 5075

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["DogMicroService/DogMicroService.csproj", "DogMicroService/"]
COPY ["CommonServices/CommonServices.csproj", "CommonServices/"]
RUN dotnet restore "DogMicroService/DogMicroService.csproj"
COPY . .
WORKDIR "/src/DogMicroService"
RUN dotnet build "./DogMicroService.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./DogMicroService.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DogMicroService.dll"]