FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 5023

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Services/Gateway/Gateway.csproj", "Services/Gateway/"]
COPY ["Libraries/CommonDto/CommonDto.csproj", "Libraries/CommonDto/"]
COPY ["Libraries/CommonServices/CommonServices.csproj", "Libraries/CommonServices/"]
RUN dotnet restore "Services/Gateway/Gateway.csproj"
COPY . .
WORKDIR "/src/Services/Gateway"
RUN dotnet build "./Gateway.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Gateway.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Gateway.dll"]