// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeedMicroService.Context;

#nullable disable

namespace SeedMicroService.Migrations
{
    [DbContext(typeof(SeedContext))]
    [Migration("20250714174706_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("SeedMicroService.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Légume feuille"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Légume fruit"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Légume racine"
                        });
                });

            modelBuilder.Entity("SeedMicroService.Entities.SeedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationBeforeHarvest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RisingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Seeds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8edc8f5-55b3-4ac7-9c23-7f9e4ca696ee"),
                            CategoryId = 1,
                            DurationBeforeHarvest = 30,
                            Name = "Batavia",
                            Picture = "",
                            RisingTime = 5,
                            Species = "Laitue"
                        },
                        new
                        {
                            Id = new Guid("f1996cad-fddf-44f3-bc72-990708096c1b"),
                            CategoryId = 2,
                            DurationBeforeHarvest = 90,
                            Name = "Saint Pierre",
                            Picture = "",
                            RisingTime = 3,
                            Species = "Tomate"
                        },
                        new
                        {
                            Id = new Guid("17e8c645-6149-44c2-8702-73867d6fef7a"),
                            CategoryId = 2,
                            DurationBeforeHarvest = 120,
                            Name = "Géante de New York",
                            Picture = "",
                            RisingTime = 10,
                            Species = "Aubergine"
                        });
                });

            modelBuilder.Entity("SeedMicroService.Entities.SeedEntity", b =>
                {
                    b.HasOne("SeedMicroService.Entities.CategoryEntity", "Category")
                        .WithMany("Seeds")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SeedMicroService.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Seeds");
                });
#pragma warning restore 612, 618
        }
    }
}
